version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pms_postgres
    environment:
      POSTGRES_USER: bala
      POSTGRES_PASSWORD: "bala@1234"
      POSTGRES_DB: pms
    ports:
      - "5432:5432"
    volumes:
      - pms_data:/var/lib/postgresql/data

volumes:
  pms_data:
